name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes: { label: Description, placeholder: What happened? }
    validations: { required: true }
  - type: textarea
    id: steps
    attributes: { label: Steps to reproduce, placeholder: 1. … }
    validations: { required: true }
  - type: input
    id: version
    attributes: { label: Affected version (e.g., v2.1.0) }
  - type: textarea
    id: logs
    attributes: { label: Logs (with Request-ID if available) }
