name: CI
on:
  pull_request:
  push:
    branches: ["**"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v6
        with: { python-version: "3.12" }
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install . ruff isort pytest pytest-django
      - name: Lint
        run: |
          ruff check .
          isort --check-only .
      - name: Test
        env:
          DJANGO_SETTINGS_MODULE: config.settings.test
        run: |
          pytest -q
